# Numpy Array Indekslenmesi ve Parçalanması

In [4]:
import numpy as np 

In [16]:
arr = np.arange(1,10)

In [18]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[2] # 3. değer

3

In [24]:
arr[3]

4

In [26]:
arr[1:5] # 1 ile 5 arası index değerleri

array([2, 3, 4, 5])

In [30]:
arr[:4] # baştan 4. indexe kadar

array([1, 2, 3, 4])

In [34]:
arr[::2] #baştan sona 2'şer atlayarak alır.

array([1, 3, 5, 7, 9])

In [36]:
arr[0:3]

array([1, 2, 3])

In [42]:
arr[:3] = 25  # ilk iç değeri değiştirme

In [44]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [46]:
arr = np.arange(1,10) 

In [48]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr2 = arr # değer değiştirme(atama)

In [56]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr2[:3] = 100

In [60]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [64]:
arr # arr2'de değer değişikliğine gittiğimiz taktirde arr'de de değerlerimiz değişmiş olacaktır.

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [69]:
arr = np.arange(1,10) 

In [71]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr2 = arr.copy() # az önceki işlemin aynısı( fakat arr2 farklı bir bellekte oluştu. Bu demek oluyor ki arr2'de yaptığımız bir değişiklik arr dizisini etkilemeyecektir

In [89]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr2[:4 ] = 12

In [93]:
arr2

array([12, 12, 12, 12,  5,  6,  7,  8,  9])

In [95]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

____

In [98]:
newArray = np.arange(1,21)

In [102]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [108]:
newArray = newArray.reshape(5,4) # 5'e 4'lük bir matrise çevirelim

In [110]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [118]:
#determinantını bulalım.
 #-> np.linalg.det(newArray) # hata alırız çinkü bu işlem için matrisimizin kare matris olması lazım

In [120]:
newArray[0,0] # ilk satırın ilk elemanı

1

In [124]:
#Tüm satırların ilk  iki değerini(ilk iki sütunu) alalım:
newArray[:,:2] # satırların hepsini al , ancak sütunların sadece ilk ikisini al.

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [128]:
newArray[:3,:3] # ilk 3

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [132]:
newArray[:2,:] # ilk iki satırın tüm sütunları

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

_____

### Numpy Arraylerinin Filtrelenmesi

In [140]:
arr = np.arange(1,11) 

In [142]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr>3 # 3'ten büyük değerlerin tru-false oluşunu kontrol edelim

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [150]:
boolValuesArray = arr > 3

In [156]:
true_array = arr[boolValuesArray]

In [158]:
true_array

array([ 4,  5,  6,  7,  8,  9, 10])

In [164]:
arr[arr > 5] # Daha kısa hali 

array([ 6,  7,  8,  9, 10])

In [ ]:
bv 