In [89]:
import numpy as np

In [90]:
# 5 tane 1 içeren array
arr = np.ones(5) # int olarak almak istersek dtype vermemiz lazım
arr
arr_int = np.ones(5, dtype = int)
arr_int

array([1, 1, 1, 1, 1])

In [91]:
# 5 tane  içeren array
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [92]:
# 0 - 100 arası 2'ye tam bölünen sayılar
arr3 = np.arange(0,101,2)
arr3

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [93]:
arr4 = np.arange(0,100,10)
arr4[arr4//10] # 0- 100 arası 10' tam bölünen sayılar dizisi
arr4

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [94]:
# 10 tane 10 içeren bir dizi oluşturma
arr = np.full(10,10)

# Diziyi yazdır
print(arr)

[10 10 10 10 10 10 10 10 10 10]


In [95]:
# 1'den 16'ya kadar değer bulunduran 4x4'lük bir matris 
matris_arr = np.arange(1,17)

matris_arr.reshape(4,4) # matrise çevirme

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [96]:
# 4x4'lük bir birim matris
arr_unit_matrix = np.eye(4)
arr_unit_matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
# birim matris determinantı 
np.linalg.det(arr_unit_matrix)

1.0

In [98]:
# 0 ile 5 arasında rastgele değerler 
arr_random = np.random.randint(0,6,5)
arr_random

array([4, 1, 1, 2, 4])

In [99]:
#5 x 5'lik bir matrisi Gaussian Distribution'a Göre(0'ın etrafında dönme) (randn() fonksiyonu) değerler üreterek oluşturma
arr_gaussian =  np.random.randn(5,5)
arr_gaussian

array([[-0.41687373,  0.10746145, -1.47329727,  1.15316586,  1.66413846],
       [-0.96150806,  1.47777469, -1.01355993, -1.35539922, -0.27485061],
       [ 0.60229089,  1.95715113,  0.06749627, -0.41640483,  0.1414542 ],
       [ 0.57643755,  0.29230526,  0.96568732,  1.79696424,  0.73356195],
       [ 0.79860502,  0.53251696, -1.24312437,  0.45295466, -0.33283918]])

In [100]:
#1 ile 5 arasındaki mesafeyi eşit parçalara bölerek 20'lik bir array oluşturma

arr_mesafe_bölme = np.linspace(1,5,20)
arr_mesafe_bölme

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

______________

In [102]:
## Array Indekslenmesi
arr  = np.arange(1,101).reshape(10,10)

In [103]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [137]:
#İndex işlemleri ile 40 tan sonraki sayıları yazdırma
arr  = np.arange(1,101).reshape(10,10)
result = arr[arr > 40]
print(result)

[ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94
  95  96  97  98  99 100]


In [149]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)


In [151]:
arr1

array([[2, 2, 0],
       [2, 1, 0],
       [0, 4, 2]])

In [153]:
arr2

array([[2, 0, 3],
       [3, 4, 4],
       [0, 3, 2]])

In [158]:
arr1.sum()

13

In [160]:
arr1.mean()

1.4444444444444444

In [162]:
arr1*arr2

array([[ 4,  0,  0],
       [ 6,  4,  0],
       [ 0, 12,  4]])