# Numpy Arraylerinin Temel Operasyonları

In [76]:
import numpy as np

In [77]:
arr = np.arange(1,10)

In [78]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([2,3,4,5,6])

In [80]:
arr1 * arr2  # Inner Product(İç Çarpım)

array([ 20,  60, 120, 200, 300])

In [81]:
arr1 + arr2 # her bir eleman kendi içinde toplanır

array([12, 23, 34, 45, 56])

In [82]:
# Farklı boyutlarda arrylerde toplama sağlayamıyoruz

In [83]:
arr1 - arr2 

array([ 8, 17, 26, 35, 44])

In [84]:
arr1

array([10, 20, 30, 40, 50])

In [85]:
arr1 + 10 # her eleman 10 ile toplanır;

array([20, 30, 40, 50, 60])

In [86]:
arr1 * 10 # her eleman 10 ile çarpılır;

array([100, 200, 300, 400, 500])

In [87]:
arr2 - 2 # her elemandan 2 çıkarılır

array([0, 1, 2, 3, 4])

In [88]:
arr2 / 3 # float döner

array([0.66666667, 1.        , 1.33333333, 1.66666667, 2.        ])

In [89]:
arr1

array([10, 20, 30, 40, 50])

In [90]:
np.sqrt(arr1) # her elemanın karekökü alnır;

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

_____

In [122]:
arr3 = np.array([4,16,36,49,64,81,100,121,144,169,196,225,256,289])

In [124]:
arr3

array([  4,  16,  36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256,
       289])

In [128]:
np.sqrt(arr3) # her elemanın karekökünü alır(kök derecesi)

array([ 2.,  4.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16.,
       17.])